name: Build
on: [push, pull_request]

jobs:
  build:
    name: bosce
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt -y update
          sudo apt -y install cmake libboost-dev libboost-filesystem-dev libboost-program-options-dev
      - name: Build 
        run: |
            mkdir build
            cd build
            cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=dist ..
            cmake --build . --target demo
            cmake --build . -- -j4
            ctest
            cmake --build . --target install
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: dist
          name: bosce-linux
